[platformio]
default_envs = esp32s3_devkitc_1
src_dir = main

[env:esp32s3_devkitc_1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = espidf
monitor_speed = 115200
monitor_filters = esp32_exception_decoder, time
board_upload.flash_size = 8MB
board_build.sdkconfig = sdkconfig.esp32s3_devkitc_1
